CREATE TABLE users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  role ENUM('admin', 'resident') NOT NULL,
  username VARCHAR(80) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE apartments (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  apartment_number INT UNSIGNED NOT NULL UNIQUE,
  floor_number INT UNSIGNED NOT NULL,
  unit_number INT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NOT NULL UNIQUE,
  resident_name VARCHAR(160) DEFAULT '',
  phone VARCHAR(40) DEFAULT '',
  occupancy ENUM('owner', 'tenant') NOT NULL DEFAULT 'owner',
  finish_status ENUM('finished', 'unfinished') NOT NULL DEFAULT 'finished',
  previous_arrears DECIMAL(10,2) NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_apartments_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE,
  UNIQUE KEY uq_apartment_floor_unit (floor_number, unit_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE payments (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  apartment_id INT UNSIGNED NOT NULL,
  service_month CHAR(7) NOT NULL,
  amount DECIMAL(10,2) NOT NULL DEFAULT 360.00,
  paid_to VARCHAR(160) NOT NULL,
  method ENUM('wallet', 'instapay', 'cash') NOT NULL DEFAULT 'wallet',
  reference_number VARCHAR(120) NOT NULL,
  paid_at DATE NOT NULL,
  receipt_path VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_payment_apartment_month (apartment_id, service_month),
  CONSTRAINT fk_payments_apartment
    FOREIGN KEY (apartment_id) REFERENCES apartments(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE expenses (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  expense_month CHAR(7) NOT NULL,
  spent_at DATE NOT NULL,
  details TEXT NOT NULL,
  invoice_path VARCHAR(255) DEFAULT NULL,
  created_by INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_expenses_user
    FOREIGN KEY (created_by) REFERENCES users(id)
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE shared_charges (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  charge_month CHAR(7) NOT NULL,
  details TEXT NOT NULL,
  created_by INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_shared_charges_user
    FOREIGN KEY (created_by) REFERENCES users(id)
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO users (role, username, password_hash, is_active)
VALUES ('admin', 'admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 1);

INSERT INTO users (role, username, password_hash, is_active)
SELECT 'resident', CONCAT('apt', n), '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 1
FROM (
  SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION
  SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION
  SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION
  SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION
  SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION
  SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION
  SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION
  SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION
  SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION
  SELECT 46 UNION SELECT 47 UNION SELECT 48
) numbers;

INSERT INTO apartments (apartment_number, floor_number, unit_number, user_id, resident_name, phone, occupancy, finish_status, previous_arrears, notes)
SELECT
  CAST(SUBSTRING(username, 4) AS UNSIGNED),
  FLOOR((CAST(SUBSTRING(username, 4) AS UNSIGNED) - 1) / 4) + 1,
  ((CAST(SUBSTRING(username, 4) AS UNSIGNED) - 1) % 4) + 1,
  id,
  CASE CAST(SUBSTRING(username, 4) AS UNSIGNED)
    WHEN 1 THEN 'الأستاذ محمد أحمد'
    WHEN 2 THEN 'الدكتور خالد إبراهيم'
    WHEN 3 THEN 'الأستاذة هالة ثروت'
    ELSE CONCAT('الساكن رقم ', CAST(SUBSTRING(username, 4) AS UNSIGNED))
  END,
  CONCAT('01010530', LPAD(198 + CAST(SUBSTRING(username, 4) AS UNSIGNED), 3, '0')),
  CASE WHEN CAST(SUBSTRING(username, 4) AS UNSIGNED) <= 10 THEN 'tenant' ELSE 'owner' END,
  CASE WHEN CAST(SUBSTRING(username, 4) AS UNSIGNED) <= 21 THEN 'finished' ELSE 'unfinished' END,
  0,
  ''
FROM users
WHERE role = 'resident';
